development:
  adapter: mysql2
  encoding: utf8
  database: ocutec_development
  username: root
  password: chimpance99
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: ocutec2_production
  username: root
  password: razm
  host: localhost

# production:
#   adapter: postgresql
#   encoding: unicode
#   pool: 5
  # host:  ec2-23-21-243-117.compute-1.amazonaws.com
  # database:  d1e8tvm3odt4g5
  # username:  rwzbbrbpsqsuct
  # port:  5432
  # password: tSERpl9b72N03x7roaJ4ZCI5Ww
